config/routes.rb
Rails.application.routes.draw do


  devise_for :accs, :controllers => { :omniauth_callbacks => "accs/omniauth_callbacks" }
  
  get "u/:username" => "public#profile", as: :profile
  resources :communities do
  resources :posts
end



resources :subscriptions
resources :comments, only: [:create]

post "post/vote" => "votes#create"
  root to: "public#index"

  root to: "photos#index"
  resources :photos
end

app/views/comments/create.js.erb
document.getElementById("post-comments").innerHTML = "<%= escape_javascript(render partial: 'posts/comments', locals: {comments: @comments }) %>";

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @community do |form| %>

    <div class="form-group">
      <%= label_tag :name %>
      <%= form.text_field :name,  class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :url %>
      <%= form.text_field :url,  class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag :summary %>
      <%= form.text_field :summary,  class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag :rules %>
      <%= form.text_area :rules,  class: "form-control" %>
    </div>


    <%= form.submit "Submit", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
<%= f.hidden_field :community_id, value: community_id %>
<%= f.submit "Join Community", class: "btn btn-success text-uppercase float-right" %>
<% end %>

app/views/communities/index.html.erb
<% if acc_signed_in? %>
<div class="float-right">
  <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
</div>
<% end %>
<% if @communities.size > 0 %>
<% @communities.each do |community| %>
<div class="card">
  <h3> <%= link_to community.name, community %> </h3>
  <div class="pd-3">
    <%= community.rules %>

  </div>

</div>
<% end %>
<% else %>
<p> No communities </p>
<% end %>

app/views/communities/new.html.erb
<h2> New Community  </h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<div class="row mb-4">
  <div class="col-sm-8">
<h3> Community name: <%= @community.name %></h3>

  </div>
  <div class="col-sm-4">
    <% if @is_subscribed %>
    <%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-right"%>
<% else %>
<%= render partial:"communities/subscribe", locals: { community_id: @community.id } %>
<% end %>
  </div>
</div>



<div class="row">
  <div class="col-sm-8">
<%= render partial: "posts/list", locals: {posts: @posts}  %>
  </div>
  <div class="col-sm-4">
    <div class="card p-3">
      <h5> About this community: </h5>
      <p class="mt-2"><%= @community.summary %></p>

    </div>
    <p><%= pluralize @subscriber_count, "member" %> </p>

    <small>
    <p> Rules here: <%= @community.rules %> </p>
    </small>

  </div>
</div>

app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<div class="media">
  <% @photos.each do |photo| %>
    <div class="media-left">
      <!-- Renders image -->
      <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
      <!-- Button to delete image -->
      <%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= photo.title %></h4>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo, html: { multipart: true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
      </h2>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/photos/show.html.erb
<%= image_tag @movie.image.url(:medium) %>

app/views/votes/create.js.erb
console.log("vote saved..");